---
- name: "install alert manager"
  shell: |
    sudo useradd --no-create-home prometheus
    sudo mkdir /etc/prometheus
    sudo mkdir /var/lib/prometheus
    wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz
    sudo cp alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin
    sudo cp alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
    sudo mkdir /var/lib/alertmanager
    rm -rf alertmanager*
- name: "add alertmanager.yml"
  become: true
  copy:
    src: alertmanager.yml
    dest: /etc/prometheus/
- name: "add alertmanager.service"
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/
- name: "start alertmanager"
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable alertmanager
    sudo systemctl start alertmanager
