---
- name: "install prometheus"
  shell: |
    sudo useradd --no-create-home prometheus
    sudo useradd --no-create-home node_exporter
    sudo mkdir /etc/prometheus
    sudo mkdir /var/lib/prometheus
    wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
    sudo cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    sudo cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    sudo cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
    sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64
    
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64
- name: "add prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/
- name: "add prometheus configuration service"
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
- name: "add node-exporter configuration service"
  become: true
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/
- name: "add rules.yml"
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/
- name: "chown step"
  shell: |
    sudo chown prometheus:prometheus /etc/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/promtool
    sudo chown -R prometheus:prometheus /etc/prometheus/consoles
    sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
    sudo chown -R prometheus:prometheus /var/lib/prometheus
- name: "start prometheus"
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable prometheus
    sudo systemctl start prometheus
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter

#- name: "restart prometheus"
#  shell: |
#    sudo systemctl restart prometheus
