groups:
  - name: udapeople_ec2
    rules:
    - alert: InstanceUp
      expr: up == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: “Instance [{{ $labels.instance }}] Running”
        description: “[{{ $labels.instance }}] of job [{{ $labels.job }}] has been up for more than 1 minute.”
